// Generated by tools/dump_filterbank.py; do not edit. Regenerate from the Python side.
//
// madmom's LogarithmicFilterbank as applied in the BeatNet+ front end (HANDOFF §5.2):
// the 882 bins of a 1764-point STFT at 22050 Hz (DC up to, not including,
// Nyquist) folded into 144 bands, 24 per octave between 30 Hz and 17000 Hz around
// 440 Hz, every filter normalised to sum 1, duplicate filters removed. Each band is one
// contiguous triangle of bins. The weights are hexadecimal float literals, so they are
// the float32 values madmom uses, exactly.
//
// Source: https://github.com/CPJKU/madmom.git @ 27f032e8947204902c675e5e341a3faf5dc86dae; numpy 2.5.2.

#include "core/features/filterbank.hpp"

namespace takt4::features {

namespace {

constexpr float kWeights[1601] = {
    0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f,
    0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f,
    0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f,
    0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f,
    0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f,
    0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f, 0x1.555556p-1f,
    0x1.555556p-2f, 0x1.555556p-2f, 0x1.555556p-1f, 0x1.0p+0f, 0x1.0p+0f, 0x1.0p+0f,
    0x1.555556p-1f, 0x1.555556p-2f, 0x1.555556p-2f, 0x1.555556p-1f, 0x1.0p+0f, 0x1.555556p-1f,
    0x1.555556p-2f, 0x1.555556p-2f, 0x1.555556p-1f, 0x1.555556p-1f, 0x1.555556p-2f, 0x1.555556p-2f,
    0x1.555556p-1f, 0x1.555556p-1f, 0x1.555556p-2f, 0x1.0p-2f, 0x1.0p-1f, 0x1.0p-2f,
    0x1.555556p-2f, 0x1.555556p-1f, 0x1.555556p-1f, 0x1.555556p-2f, 0x1.0p-2f, 0x1.0p-1f,
    0x1.0p-2f, 0x1.0p-2f, 0x1.0p-1f, 0x1.0p-2f, 0x1.555556p-2f, 0x1.555556p-1f,
    0x1.555556p-1f, 0x1.555556p-2f, 0x1.0p-2f, 0x1.0p-1f, 0x1.0p-2f, 0x1.0p-2f,
    0x1.0p-1f, 0x1.0p-2f, 0x1.99999ap-3f, 0x1.99999ap-2f, 0x1.111112p-2f, 0x1.111112p-3f,
    0x1.111112p-3f, 0x1.111112p-2f, 0x1.99999ap-2f, 0x1.99999ap-3f, 0x1.0p-2f, 0x1.0p-1f,
    0x1.0p-2f, 0x1.0p-2f, 0x1.0p-1f, 0x1.0p-2f, 0x1.99999ap-3f, 0x1.99999ap-2f,
    0x1.111112p-2f, 0x1.111112p-3f, 0x1.111112p-3f, 0x1.111112p-2f, 0x1.99999ap-2f, 0x1.99999ap-3f,
    0x1.99999ap-3f, 0x1.99999ap-2f, 0x1.111112p-2f, 0x1.111112p-3f, 0x1.111112p-3f, 0x1.111112p-2f,
    0x1.99999ap-2f, 0x1.99999ap-3f, 0x1.99999ap-3f, 0x1.99999ap-2f, 0x1.111112p-2f, 0x1.111112p-3f,
    0x1.c71c72p-4f, 0x1.c71c72p-3f, 0x1.555556p-2f, 0x1.c71c72p-3f, 0x1.c71c72p-4f, 0x1.c71c72p-4f,
    0x1.c71c72p-3f, 0x1.555556p-2f, 0x1.c71c72p-3f, 0x1.c71c72p-4f, 0x1.111112p-3f, 0x1.111112p-2f,
    0x1.99999ap-2f, 0x1.99999ap-3f, 0x1.99999ap-3f, 0x1.99999ap-2f, 0x1.111112p-2f, 0x1.111112p-3f,
    0x1.861862p-4f, 0x1.861862p-3f, 0x1.24924ap-2f, 0x1.b6db6ep-3f, 0x1.24924ap-3f, 0x1.24924ap-4f,
    0x1.24924ap-4f, 0x1.24924ap-3f, 0x1.b6db6ep-3f, 0x1.24924ap-2f, 0x1.861862p-3f, 0x1.861862p-4f,
    0x1.c71c72p-4f, 0x1.c71c72p-3f, 0x1.555556p-2f, 0x1.c71c72p-3f, 0x1.c71c72p-4f, 0x1.c71c72p-4f,
    0x1.c71c72p-3f, 0x1.555556p-2f, 0x1.c71c72p-3f, 0x1.c71c72p-4f, 0x1.861862p-4f, 0x1.861862p-3f,
    0x1.24924ap-2f, 0x1.b6db6ep-3f, 0x1.24924ap-3f, 0x1.24924ap-4f, 0x1.24924ap-4f, 0x1.24924ap-3f,
    0x1.b6db6ep-3f, 0x1.24924ap-2f, 0x1.861862p-3f, 0x1.861862p-4f, 0x1.861862p-4f, 0x1.861862p-3f,
    0x1.24924ap-2f, 0x1.b6db6ep-3f, 0x1.24924ap-3f, 0x1.24924ap-4f, 0x1.0p-4f, 0x1.0p-3f,
    0x1.8p-3f, 0x1.0p-2f, 0x1.8p-3f, 0x1.0p-3f, 0x1.0p-4f, 0x1.0p-4f,
    0x1.0p-3f, 0x1.8p-3f, 0x1.0p-2f, 0x1.8p-3f, 0x1.0p-3f, 0x1.0p-4f,
    0x1.0p-4f, 0x1.0p-3f, 0x1.8p-3f, 0x1.0p-2f, 0x1.8p-3f, 0x1.0p-3f,
    0x1.0p-4f, 0x1.0p-4f, 0x1.0p-3f, 0x1.8p-3f, 0x1.0p-2f, 0x1.8p-3f,
    0x1.0p-3f, 0x1.0p-4f, 0x1.0p-4f, 0x1.0p-3f, 0x1.8p-3f, 0x1.0p-2f,
    0x1.8p-3f, 0x1.0p-3f, 0x1.0p-4f, 0x1.c71c72p-5f, 0x1.c71c72p-4f, 0x1.555556p-3f,
    0x1.c71c72p-3f, 0x1.6c16c2p-3f, 0x1.111112p-3f, 0x1.6c16c2p-4f, 0x1.6c16c2p-5f, 0x1.6c16c2p-5f,
    0x1.6c16c2p-4f, 0x1.111112p-3f, 0x1.6c16c2p-3f, 0x1.c71c72p-3f, 0x1.555556p-3f, 0x1.c71c72p-4f,
    0x1.c71c72p-5f, 0x1.c71c72p-5f, 0x1.c71c72p-4f, 0x1.555556p-3f, 0x1.c71c72p-3f, 0x1.6c16c2p-3f,
    0x1.111112p-3f, 0x1.6c16c2p-4f, 0x1.6c16c2p-5f, 0x1.6c16c2p-5f, 0x1.6c16c2p-4f, 0x1.111112p-3f,
    0x1.6c16c2p-3f, 0x1.c71c72p-3f, 0x1.555556p-3f, 0x1.c71c72p-4f, 0x1.c71c72p-5f, 0x1.c71c72p-5f,
    0x1.c71c72p-4f, 0x1.555556p-3f, 0x1.c71c72p-3f, 0x1.6c16c2p-3f, 0x1.111112p-3f, 0x1.6c16c2p-4f,
    0x1.6c16c2p-5f, 0x1.47ae14p-5f, 0x1.47ae14p-4f, 0x1.eb852p-4f, 0x1.47ae14p-3f, 0x1.99999ap-3f,
    0x1.47ae14p-3f, 0x1.eb852p-4f, 0x1.47ae14p-4f, 0x1.47ae14p-5f, 0x1.29e412p-5f, 0x1.29e412p-4f,
    0x1.bed61ep-4f, 0x1.29e412p-3f, 0x1.745d18p-3f, 0x1.364d92p-3f, 0x1.f07c2p-4f, 0x1.745d18p-4f,
    0x1.f07c2p-5f, 0x1.f07c2p-6f, 0x1.f07c2p-6f, 0x1.f07c2p-5f, 0x1.745d18p-4f, 0x1.f07c2p-4f,
    0x1.364d92p-3f, 0x1.745d18p-3f, 0x1.29e412p-3f, 0x1.bed61ep-4f, 0x1.29e412p-4f, 0x1.29e412p-5f,
    0x1.47ae14p-5f, 0x1.47ae14p-4f, 0x1.eb852p-4f, 0x1.47ae14p-3f, 0x1.99999ap-3f, 0x1.47ae14p-3f,
    0x1.eb852p-4f, 0x1.47ae14p-4f, 0x1.47ae14p-5f, 0x1.29e412p-5f, 0x1.29e412p-4f, 0x1.bed61ep-4f,
    0x1.29e412p-3f, 0x1.745d18p-3f, 0x1.364d92p-3f, 0x1.f07c2p-4f, 0x1.745d18p-4f, 0x1.f07c2p-5f,
    0x1.f07c2p-6f, 0x1.c71c76p-6f, 0x1.c71c76p-5f, 0x1.555558p-4f, 0x1.c71c76p-4f, 0x1.1c71c8p-3f,
    0x1.555558p-3f, 0x1.1c71c8p-3f, 0x1.c71c76p-4f, 0x1.555558p-4f, 0x1.c71c76p-5f, 0x1.c71c76p-6f,
    0x1.c71c76p-6f, 0x1.c71c76p-5f, 0x1.555558p-4f, 0x1.c71c76p-4f, 0x1.1c71c8p-3f, 0x1.555558p-3f,
    0x1.1c71c8p-3f, 0x1.c71c76p-4f, 0x1.555558p-4f, 0x1.c71c76p-5f, 0x1.c71c76p-6f, 0x1.c71c76p-6f,
    0x1.c71c76p-5f, 0x1.555558p-4f, 0x1.c71c76p-4f, 0x1.1c71c8p-3f, 0x1.555558p-3f, 0x1.1c71c8p-3f,
    0x1.c71c76p-4f, 0x1.555558p-4f, 0x1.c71c76p-5f, 0x1.c71c76p-6f, 0x1.a41a42p-6f, 0x1.a41a42p-5f,
    0x1.3b13b2p-4f, 0x1.a41a42p-4f, 0x1.069068p-3f, 0x1.3b13b2p-3f, 0x1.0e10e2p-3f, 0x1.c21c22p-4f,
    0x1.681682p-4f, 0x1.0e10e2p-4f, 0x1.681682p-5f, 0x1.681682p-6f, 0x1.681682p-6f, 0x1.681682p-5f,
    0x1.0e10e2p-4f, 0x1.681682p-4f, 0x1.c21c22p-4f, 0x1.0e10e2p-3f, 0x1.3b13b2p-3f, 0x1.069068p-3f,
    0x1.a41a42p-4f, 0x1.3b13b2p-4f, 0x1.a41a42p-5f, 0x1.a41a42p-6f, 0x1.a41a42p-6f, 0x1.a41a42p-5f,
    0x1.3b13b2p-4f, 0x1.a41a42p-4f, 0x1.069068p-3f, 0x1.3b13b2p-3f, 0x1.0e10e2p-3f, 0x1.c21c22p-4f,
    0x1.681682p-4f, 0x1.0e10e2p-4f, 0x1.681682p-5f, 0x1.681682p-6f, 0x1.4e5e0cp-6f, 0x1.4e5e0cp-5f,
    0x1.f58d1p-5f, 0x1.4e5e0cp-4f, 0x1.a1f58ep-4f, 0x1.f58d1p-4f, 0x1.24924ap-3f, 0x1.f58d1p-4f,
    0x1.a1f58ep-4f, 0x1.4e5e0cp-4f, 0x1.f58d1p-5f, 0x1.4e5e0cp-5f, 0x1.4e5e0cp-6f, 0x1.4e5e0cp-6f,
    0x1.4e5e0cp-5f, 0x1.f58d1p-5f, 0x1.4e5e0cp-4f, 0x1.a1f58ep-4f, 0x1.f58d1p-4f, 0x1.24924ap-3f,
    0x1.f58d1p-4f, 0x1.a1f58ep-4f, 0x1.4e5e0cp-4f, 0x1.f58d1p-5f, 0x1.4e5e0cp-5f, 0x1.4e5e0cp-6f,
    0x1.4e5e0cp-6f, 0x1.4e5e0cp-5f, 0x1.f58d1p-5f, 0x1.4e5e0cp-4f, 0x1.a1f58ep-4f, 0x1.f58d1p-4f,
    0x1.24924ap-3f, 0x1.f58d1p-4f, 0x1.a1f58ep-4f, 0x1.4e5e0cp-4f, 0x1.f58d1p-5f, 0x1.4e5e0cp-5f,
    0x1.4e5e0cp-6f, 0x1.381382p-6f, 0x1.381382p-5f, 0x1.d41d42p-5f, 0x1.381382p-4f, 0x1.861862p-4f,
    0x1.d41d42p-4f, 0x1.111112p-3f, 0x1.dddddep-4f, 0x1.99999ap-4f, 0x1.555556p-4f, 0x1.111112p-4f,
    0x1.99999ap-5f, 0x1.111112p-5f, 0x1.111112p-6f, 0x1.0p-6f, 0x1.0p-5f, 0x1.8p-5f,
    0x1.0p-4f, 0x1.4p-4f, 0x1.8p-4f, 0x1.cp-4f, 0x1.0p-3f, 0x1.cp-4f,
    0x1.8p-4f, 0x1.4p-4f, 0x1.0p-4f, 0x1.8p-5f, 0x1.0p-5f, 0x1.0p-6f,
    0x1.0p-6f, 0x1.0p-5f, 0x1.8p-5f, 0x1.0p-4f, 0x1.4p-4f, 0x1.8p-4f,
    0x1.cp-4f, 0x1.0p-3f, 0x1.cp-4f, 0x1.8p-4f, 0x1.4p-4f, 0x1.0p-4f,
    0x1.8p-5f, 0x1.0p-5f, 0x1.0p-6f, 0x1.0p-6f, 0x1.0p-5f, 0x1.8p-5f,
    0x1.0p-4f, 0x1.4p-4f, 0x1.8p-4f, 0x1.cp-4f, 0x1.0p-3f, 0x1.cp-4f,
    0x1.8p-4f, 0x1.4p-4f, 0x1.0p-4f, 0x1.8p-5f, 0x1.0p-5f, 0x1.0p-6f,
    0x1.0p-6f, 0x1.0p-5f, 0x1.8p-5f, 0x1.0p-4f, 0x1.4p-4f, 0x1.8p-4f,
    0x1.cp-4f, 0x1.0p-3f, 0x1.cp-4f, 0x1.8p-4f, 0x1.4p-4f, 0x1.0p-4f,
    0x1.8p-5f, 0x1.0p-5f, 0x1.0p-6f, 0x1.e1e1e2p-7f, 0x1.e1e1e2p-6f, 0x1.69696ap-5f,
    0x1.e1e1e2p-5f, 0x1.2d2d2ep-4f, 0x1.69696ap-4f, 0x1.a5a5a6p-4f, 0x1.e1e1e2p-4f, 0x1.ac5702p-4f,
    0x1.76cc22p-4f, 0x1.414142p-4f, 0x1.0bb662p-4f, 0x1.ac5702p-5f, 0x1.414142p-5f, 0x1.ac5702p-6f,
    0x1.ac5702p-7f, 0x1.948b1p-7f, 0x1.948b1p-6f, 0x1.2f684cp-5f, 0x1.948b1p-5f, 0x1.f9add6p-5f,
    0x1.2f684cp-4f, 0x1.61f9aep-4f, 0x1.948b1p-4f, 0x1.c71c72p-4f, 0x1.948b1p-4f, 0x1.61f9aep-4f,
    0x1.2f684cp-4f, 0x1.f9add6p-5f, 0x1.948b1p-5f, 0x1.2f684cp-5f, 0x1.948b1p-6f, 0x1.948b1p-7f,
    0x1.948b1p-7f, 0x1.948b1p-6f, 0x1.2f684cp-5f, 0x1.948b1p-5f, 0x1.f9add6p-5f, 0x1.2f684cp-4f,
    0x1.61f9aep-4f, 0x1.948b1p-4f, 0x1.c71c72p-4f, 0x1.948b1p-4f, 0x1.61f9aep-4f, 0x1.2f684cp-4f,
    0x1.f9add6p-5f, 0x1.948b1p-5f, 0x1.2f684cp-5f, 0x1.948b1p-6f, 0x1.948b1p-7f, 0x1.7f406p-7f,
    0x1.7f406p-6f, 0x1.1f7048p-5f, 0x1.7f406p-5f, 0x1.df107ap-5f, 0x1.1f7048p-4f, 0x1.4f5854p-4f,
    0x1.7f406p-4f, 0x1.af286cp-4f, 0x1.840ac6p-4f, 0x1.58ed24p-4f, 0x1.2dcf7ep-4f, 0x1.02b1dap-4f,
    0x1.af286cp-5f, 0x1.58ed24p-5f, 0x1.02b1dap-5f, 0x1.58ed24p-6f, 0x1.58ed24p-7f, 0x1.47ae14p-7f,
    0x1.47ae14p-6f, 0x1.eb852p-6f, 0x1.47ae14p-5f, 0x1.99999ap-5f, 0x1.eb852p-5f, 0x1.1eb852p-4f,
    0x1.47ae14p-4f, 0x1.70a3d6p-4f, 0x1.99999ap-4f, 0x1.70a3d6p-4f, 0x1.47ae14p-4f, 0x1.1eb852p-4f,
    0x1.eb852p-5f, 0x1.99999ap-5f, 0x1.47ae14p-5f, 0x1.eb852p-6f, 0x1.47ae14p-6f, 0x1.47ae14p-7f,
    0x1.47ae14p-7f, 0x1.47ae14p-6f, 0x1.eb852p-6f, 0x1.47ae14p-5f, 0x1.99999ap-5f, 0x1.eb852p-5f,
    0x1.1eb852p-4f, 0x1.47ae14p-4f, 0x1.70a3d6p-4f, 0x1.99999ap-4f, 0x1.70a3d6p-4f, 0x1.47ae14p-4f,
    0x1.1eb852p-4f, 0x1.eb852p-5f, 0x1.99999ap-5f, 0x1.47ae14p-5f, 0x1.eb852p-6f, 0x1.47ae14p-6f,
    0x1.47ae14p-7f, 0x1.47ae14p-7f, 0x1.47ae14p-6f, 0x1.eb852p-6f, 0x1.47ae14p-5f, 0x1.99999ap-5f,
    0x1.eb852p-5f, 0x1.1eb852p-4f, 0x1.47ae14p-4f, 0x1.70a3d6p-4f, 0x1.99999ap-4f, 0x1.70a3d6p-4f,
    0x1.47ae14p-4f, 0x1.1eb852p-4f, 0x1.eb852p-5f, 0x1.99999ap-5f, 0x1.47ae14p-5f, 0x1.eb852p-6f,
    0x1.47ae14p-6f, 0x1.47ae14p-7f, 0x1.381384p-7f, 0x1.381384p-6f, 0x1.d41d46p-6f, 0x1.381384p-5f,
    0x1.861864p-5f, 0x1.d41d46p-5f, 0x1.111112p-4f, 0x1.381384p-4f, 0x1.5f15f2p-4f, 0x1.861864p-4f,
    0x1.62a1dp-4f, 0x1.3f2b3ap-4f, 0x1.1bb4a6p-4f, 0x1.f07c22p-5f, 0x1.a98efap-5f, 0x1.62a1dp-5f,
    0x1.1bb4a6p-5f, 0x1.a98efap-6f, 0x1.1bb4a6p-6f, 0x1.1bb4a6p-7f, 0x1.0ecf58p-7f, 0x1.0ecf58p-6f,
    0x1.963706p-6f, 0x1.0ecf58p-5f, 0x1.52833p-5f, 0x1.963706p-5f, 0x1.d9eadap-5f, 0x1.0ecf58p-4f,
    0x1.30a944p-4f, 0x1.52833p-4f, 0x1.745d1ap-4f, 0x1.52833p-4f, 0x1.30a944p-4f, 0x1.0ecf58p-4f,
    0x1.d9eadap-5f, 0x1.963706p-5f, 0x1.52833p-5f, 0x1.0ecf58p-5f, 0x1.963706p-6f, 0x1.0ecf58p-6f,
    0x1.0ecf58p-7f, 0x1.0ecf58p-7f, 0x1.0ecf58p-6f, 0x1.963706p-6f, 0x1.0ecf58p-5f, 0x1.52833p-5f,
    0x1.963706p-5f, 0x1.d9eadap-5f, 0x1.0ecf58p-4f, 0x1.30a944p-4f, 0x1.52833p-4f, 0x1.745d1ap-4f,
    0x1.52833p-4f, 0x1.30a944p-4f, 0x1.0ecf58p-4f, 0x1.d9eadap-5f, 0x1.963706p-5f, 0x1.52833p-5f,
    0x1.0ecf58p-5f, 0x1.963706p-6f, 0x1.0ecf58p-6f, 0x1.0ecf58p-7f, 0x1.03091ep-7f, 0x1.03091ep-6f,
    0x1.848dacp-6f, 0x1.03091ep-5f, 0x1.43cb64p-5f, 0x1.848dacp-5f, 0x1.c54ff2p-5f, 0x1.03091ep-4f,
    0x1.236a4p-4f, 0x1.43cb64p-4f, 0x1.642c88p-4f, 0x1.467e28p-4f, 0x1.28cfc6p-4f, 0x1.0b2166p-4f,
    0x1.dae60ap-5f, 0x1.9f8948p-5f, 0x1.642c88p-5f, 0x1.28cfc6p-5f, 0x1.dae60ap-6f, 0x1.642c88p-6f,
    0x1.dae60ap-7f, 0x1.dae60ap-8f, 0x1.c71c72p-8f, 0x1.c71c72p-7f, 0x1.555556p-6f, 0x1.c71c72p-6f,
    0x1.1c71c6p-5f, 0x1.555556p-5f, 0x1.8e38e2p-5f, 0x1.c71c72p-5f, 0x1.0p-4f, 0x1.1c71c6p-4f,
    0x1.38e38ep-4f, 0x1.555556p-4f, 0x1.38e38ep-4f, 0x1.1c71c6p-4f, 0x1.0p-4f, 0x1.c71c72p-5f,
    0x1.8e38e2p-5f, 0x1.555556p-5f, 0x1.1c71c6p-5f, 0x1.c71c72p-6f, 0x1.555556p-6f, 0x1.c71c72p-7f,
    0x1.c71c72p-8f, 0x1.c71c72p-8f, 0x1.c71c72p-7f, 0x1.555556p-6f, 0x1.c71c72p-6f, 0x1.1c71c6p-5f,
    0x1.555556p-5f, 0x1.8e38e2p-5f, 0x1.c71c72p-5f, 0x1.0p-4f, 0x1.1c71c6p-4f, 0x1.38e38ep-4f,
    0x1.555556p-4f, 0x1.38e38ep-4f, 0x1.1c71c6p-4f, 0x1.0p-4f, 0x1.c71c72p-5f, 0x1.8e38e2p-5f,
    0x1.555556p-5f, 0x1.1c71c6p-5f, 0x1.c71c72p-6f, 0x1.555556p-6f, 0x1.c71c72p-7f, 0x1.c71c72p-8f,
    0x1.b4e81ap-8f, 0x1.b4e81ap-7f, 0x1.47ae12p-6f, 0x1.b4e81ap-6f, 0x1.11111p-5f, 0x1.47ae12p-5f,
    0x1.7e4b16p-5f, 0x1.b4e81ap-5f, 0x1.eb851cp-5f, 0x1.11111p-4f, 0x1.2c5f92p-4f, 0x1.47ae12p-4f,
    0x1.2e794cp-4f, 0x1.154486p-4f, 0x1.f81f8p-5f, 0x1.c5b5f4p-5f, 0x1.934c66p-5f, 0x1.60e2dap-5f,
    0x1.2e794cp-5f, 0x1.f81f8p-6f, 0x1.934c66p-6f, 0x1.2e794cp-6f, 0x1.934c66p-7f, 0x1.934c66p-8f,
    0x1.83c978p-8f, 0x1.83c978p-7f, 0x1.22d71ap-6f, 0x1.83c978p-6f, 0x1.e4bbd6p-6f, 0x1.22d71ap-5f,
    0x1.53504ap-5f, 0x1.83c978p-5f, 0x1.b442a8p-5f, 0x1.e4bbd6p-5f, 0x1.0a9a82p-4f, 0x1.22d71ap-4f,
    0x1.3b13b2p-4f, 0x1.22d71ap-4f, 0x1.0a9a82p-4f, 0x1.e4bbd6p-5f, 0x1.b442a8p-5f, 0x1.83c978p-5f,
    0x1.53504ap-5f, 0x1.22d71ap-5f, 0x1.e4bbd6p-6f, 0x1.83c978p-6f, 0x1.22d71ap-6f, 0x1.83c978p-7f,
    0x1.83c978p-8f, 0x1.756caep-8f, 0x1.756caep-7f, 0x1.181182p-6f, 0x1.756caep-6f, 0x1.d2c7d8p-6f,
    0x1.181182p-5f, 0x1.46bf18p-5f, 0x1.756caep-5f, 0x1.a41a42p-5f, 0x1.d2c7d8p-5f, 0x1.00bab6p-4f,
    0x1.181182p-4f, 0x1.2f684cp-4f, 0x1.19bc46p-4f, 0x1.041042p-4f, 0x1.dcc876p-5f, 0x1.b1706ep-5f,
    0x1.861862p-5f, 0x1.5ac058p-5f, 0x1.2f684cp-5f, 0x1.041042p-5f, 0x1.b1706ep-6f, 0x1.5ac058p-6f,
    0x1.041042p-6f, 0x1.5ac058p-7f, 0x1.5ac058p-8f, 0x1.5ac058p-8f, 0x1.5ac058p-7f, 0x1.041042p-6f,
    0x1.5ac058p-6f, 0x1.b1706ep-6f, 0x1.041042p-5f, 0x1.2f684cp-5f, 0x1.5ac058p-5f, 0x1.861862p-5f,
    0x1.b1706ep-5f, 0x1.dcc876p-5f, 0x1.041042p-4f, 0x1.19bc46p-4f, 0x1.2f684cp-4f, 0x1.181182p-4f,
    0x1.00bab6p-4f, 0x1.d2c7d8p-5f, 0x1.a41a42p-5f, 0x1.756caep-5f, 0x1.46bf18p-5f, 0x1.181182p-5f,
    0x1.d2c7d8p-6f, 0x1.756caep-6f, 0x1.181182p-6f, 0x1.756caep-7f, 0x1.756caep-8f, 0x1.681682p-8f,
    0x1.681682p-7f, 0x1.0e10e2p-6f, 0x1.681682p-6f, 0x1.c21c22p-6f, 0x1.0e10e2p-5f, 0x1.3b13b2p-5f,
    0x1.681682p-5f, 0x1.951952p-5f, 0x1.c21c22p-5f, 0x1.ef1ef2p-5f, 0x1.0e10e2p-4f, 0x1.24924ap-4f,
    0x1.111112p-4f, 0x1.fb1fb2p-5f, 0x1.d41d42p-5f, 0x1.ad1ad2p-5f, 0x1.861862p-5f, 0x1.5f15f2p-5f,
    0x1.381382p-5f, 0x1.111112p-5f, 0x1.d41d42p-6f, 0x1.861862p-6f, 0x1.381382p-6f, 0x1.d41d42p-7f,
    0x1.381382p-7f, 0x1.381382p-8f, 0x1.2d50a2p-8f, 0x1.2d50a2p-7f, 0x1.c3f8fp-7f, 0x1.2d50a2p-6f,
    0x1.78a4c8p-6f, 0x1.c3f8fp-6f, 0x1.07a68cp-5f, 0x1.2d50a2p-5f, 0x1.52fab4p-5f, 0x1.78a4c8p-5f,
    0x1.9e4edcp-5f, 0x1.c3f8fp-5f, 0x1.e9a304p-5f, 0x1.07a68cp-4f, 0x1.1a7b96p-4f, 0x1.064e3p-4f,
    0x1.e44194p-5f, 0x1.bbe6c6p-5f, 0x1.938bfcp-5f, 0x1.6b312ep-5f, 0x1.42d664p-5f, 0x1.1a7b96p-5f,
    0x1.e44194p-6f, 0x1.938bfcp-6f, 0x1.42d664p-6f, 0x1.e44194p-7f, 0x1.42d664p-7f, 0x1.42d664p-8f,
    0x1.381382p-8f, 0x1.381382p-7f, 0x1.d41d42p-7f, 0x1.381382p-6f, 0x1.861862p-6f, 0x1.d41d42p-6f,
    0x1.111112p-5f, 0x1.381382p-5f, 0x1.5f15f2p-5f, 0x1.861862p-5f, 0x1.ad1ad2p-5f, 0x1.d41d42p-5f,
    0x1.fb1fb2p-5f, 0x1.111112p-4f, 0x1.0p-4f, 0x1.dddddep-5f, 0x1.bbbbbcp-5f, 0x1.99999ap-5f,
    0x1.777778p-5f, 0x1.555556p-5f, 0x1.333334p-5f, 0x1.111112p-5f, 0x1.dddddep-6f, 0x1.99999ap-6f,
    0x1.555556p-6f, 0x1.111112p-6f, 0x1.99999ap-7f, 0x1.111112p-7f, 0x1.111112p-8f, 0x1.084212p-8f,
    0x1.084212p-7f, 0x1.8c631cp-7f, 0x1.084212p-6f, 0x1.4a5298p-6f, 0x1.8c631cp-6f, 0x1.ce73ap-6f,
    0x1.084212p-5f, 0x1.294a54p-5f, 0x1.4a5298p-5f, 0x1.6b5adap-5f, 0x1.8c631cp-5f, 0x1.ad6b5ep-5f,
    0x1.ce73ap-5f, 0x1.ef7be2p-5f, 0x1.084212p-4f, 0x1.ed4822p-5f, 0x1.ca0c2p-5f, 0x1.a6d01ep-5f,
    0x1.83941cp-5f, 0x1.60581ap-5f, 0x1.3d1c18p-5f, 0x1.19e014p-5f, 0x1.ed4822p-6f, 0x1.a6d01ep-6f,
    0x1.60581ap-6f, 0x1.19e014p-6f, 0x1.a6d01ep-7f, 0x1.19e014p-7f, 0x1.19e014p-8f, 0x1.19e012p-8f,
    0x1.19e012p-7f, 0x1.a6d01ap-7f, 0x1.19e012p-6f, 0x1.605816p-6f, 0x1.a6d01ap-6f, 0x1.ed481ep-6f,
    0x1.19e012p-5f, 0x1.3d1c14p-5f, 0x1.605816p-5f, 0x1.839418p-5f, 0x1.a6d01ap-5f, 0x1.ca0c1cp-5f,
    0x1.ed481ep-5f, 0x1.08421p-4f, 0x1.ef7bdep-5f, 0x1.ce739cp-5f, 0x1.ad6b5ap-5f, 0x1.8c6318p-5f,
    0x1.6b5ad6p-5f, 0x1.4a5294p-5f, 0x1.294a52p-5f, 0x1.08421p-5f, 0x1.ce739cp-6f, 0x1.8c6318p-6f,
    0x1.4a5294p-6f, 0x1.08421p-6f, 0x1.8c6318p-7f, 0x1.08421p-7f, 0x1.08421p-8f, 0x1.f07c2p-9f,
    0x1.f07c2p-8f, 0x1.745d18p-7f, 0x1.f07c2p-7f, 0x1.364d94p-6f, 0x1.745d18p-6f, 0x1.b26c9cp-6f,
    0x1.f07c2p-6f, 0x1.1745d2p-5f, 0x1.364d94p-5f, 0x1.555556p-5f, 0x1.745d18p-5f, 0x1.9364dap-5f,
    0x1.b26c9cp-5f, 0x1.d1745ep-5f, 0x1.f07c2p-5f, 0x1.d347a4p-5f, 0x1.b6132ap-5f, 0x1.98debp-5f,
    0x1.7baa36p-5f, 0x1.5e75bcp-5f, 0x1.414142p-5f, 0x1.240cc8p-5f, 0x1.06d84ep-5f, 0x1.d347a4p-6f,
    0x1.98debp-6f, 0x1.5e75bcp-6f, 0x1.240cc8p-6f, 0x1.d347a4p-7f, 0x1.5e75bcp-7f, 0x1.d347a4p-8f,
    0x1.d347a4p-9f, 0x1.c5894ep-9f, 0x1.c5894ep-8f, 0x1.5426fap-7f, 0x1.c5894ep-7f, 0x1.1b75dp-6f,
    0x1.5426fap-6f, 0x1.8cd824p-6f, 0x1.c5894ep-6f, 0x1.fe3a78p-6f, 0x1.1b75dp-5f, 0x1.37ce66p-5f,
    0x1.5426fap-5f, 0x1.707f9p-5f, 0x1.8cd824p-5f, 0x1.a930b8p-5f, 0x1.c5894ep-5f, 0x1.e1e1e2p-5f,
    0x1.c5894ep-5f, 0x1.a930b8p-5f, 0x1.8cd824p-5f, 0x1.707f9p-5f, 0x1.5426fap-5f, 0x1.37ce66p-5f,
    0x1.1b75dp-5f, 0x1.fe3a78p-6f, 0x1.c5894ep-6f, 0x1.8cd824p-6f, 0x1.5426fap-6f, 0x1.1b75dp-6f,
    0x1.c5894ep-7f, 0x1.5426fap-7f, 0x1.c5894ep-8f, 0x1.c5894ep-9f, 0x1.c5894ep-9f, 0x1.c5894ep-8f,
    0x1.5426fap-7f, 0x1.c5894ep-7f, 0x1.1b75dp-6f, 0x1.5426fap-6f, 0x1.8cd824p-6f, 0x1.c5894ep-6f,
    0x1.fe3a78p-6f, 0x1.1b75dp-5f, 0x1.37ce66p-5f, 0x1.5426fap-5f, 0x1.707f9p-5f, 0x1.8cd824p-5f,
    0x1.a930b8p-5f, 0x1.c5894ep-5f, 0x1.e1e1e2p-5f, 0x1.c5894ep-5f, 0x1.a930b8p-5f, 0x1.8cd824p-5f,
    0x1.707f9p-5f, 0x1.5426fap-5f, 0x1.37ce66p-5f, 0x1.1b75dp-5f, 0x1.fe3a78p-6f, 0x1.c5894ep-6f,
    0x1.8cd824p-6f, 0x1.5426fap-6f, 0x1.1b75dp-6f, 0x1.c5894ep-7f, 0x1.5426fap-7f, 0x1.c5894ep-8f,
    0x1.c5894ep-9f, 0x1.b89402p-9f, 0x1.b89402p-8f, 0x1.4a6f02p-7f, 0x1.b89402p-7f, 0x1.135c82p-6f,
    0x1.4a6f02p-6f, 0x1.818182p-6f, 0x1.b89402p-6f, 0x1.efa684p-6f, 0x1.135c82p-5f, 0x1.2ee5c2p-5f,
    0x1.4a6f02p-5f, 0x1.65f842p-5f, 0x1.818182p-5f, 0x1.9d0ac2p-5f, 0x1.b89402p-5f, 0x1.d41d42p-5f,
    0x1.ba1bap-5f, 0x1.a01a02p-5f, 0x1.86186p-5f, 0x1.6c16c2p-5f, 0x1.52152p-5f, 0x1.381382p-5f,
    0x1.1e11ep-5f, 0x1.041042p-5f, 0x1.d41d42p-6f, 0x1.a01a02p-6f, 0x1.6c16c2p-6f, 0x1.381382p-6f,
    0x1.041042p-6f, 0x1.a01a02p-7f, 0x1.381382p-7f, 0x1.a01a02p-8f, 0x1.a01a02p-9f, 0x1.899c12p-9f,
    0x1.899c12p-8f, 0x1.27350ep-7f, 0x1.899c12p-7f, 0x1.ec0318p-7f, 0x1.27350ep-6f, 0x1.58689p-6f,
    0x1.899c12p-6f, 0x1.bacf94p-6f, 0x1.ec0318p-6f, 0x1.0e9b4cp-5f, 0x1.27350ep-5f, 0x1.3fcecep-5f,
    0x1.58689p-5f, 0x1.71025p-5f, 0x1.899c12p-5f, 0x1.a235d2p-5f, 0x1.bacf94p-5f, 0x1.a3814ap-5f,
    0x1.8c32fep-5f, 0x1.74e4b2p-5f, 0x1.5d9668p-5f, 0x1.46481cp-5f, 0x1.2ef9d2p-5f, 0x1.17ab86p-5f,
    0x1.005d3ap-5f, 0x1.d21dep-6f, 0x1.a3814ap-6f, 0x1.74e4b2p-6f, 0x1.46481cp-6f, 0x1.17ab86p-6f,
    0x1.d21dep-7f, 0x1.74e4b2p-7f, 0x1.17ab86p-7f, 0x1.74e4b2p-8f, 0x1.74e4b2p-9f, 0x1.6b149p-9f,
    0x1.6b149p-8f, 0x1.104f6cp-7f, 0x1.6b149p-7f, 0x1.c5d9b6p-7f, 0x1.104f6cp-6f, 0x1.3db1fep-6f,
    0x1.6b149p-6f, 0x1.987724p-6f, 0x1.c5d9b6p-6f, 0x1.f33c46p-6f, 0x1.104f6cp-5f, 0x1.2700b6p-5f,
    0x1.3db1fep-5f, 0x1.546348p-5f, 0x1.6b149p-5f, 0x1.81c5dap-5f, 0x1.987724p-5f, 0x1.af286cp-5f,
    0x1.987724p-5f, 0x1.81c5dap-5f, 0x1.6b149p-5f, 0x1.546348p-5f, 0x1.3db1fep-5f, 0x1.2700b6p-5f,
    0x1.104f6cp-5f, 0x1.f33c46p-6f, 0x1.c5d9b6p-6f, 0x1.987724p-6f, 0x1.6b149p-6f, 0x1.3db1fep-6f,
    0x1.104f6cp-6f, 0x1.c5d9b6p-7f, 0x1.6b149p-7f, 0x1.104f6cp-7f, 0x1.6b149p-8f, 0x1.6b149p-9f,
    0x1.6b149p-9f, 0x1.6b149p-8f, 0x1.104f6cp-7f, 0x1.6b149p-7f, 0x1.c5d9b6p-7f, 0x1.104f6cp-6f,
    0x1.3db1fep-6f, 0x1.6b149p-6f, 0x1.987724p-6f, 0x1.c5d9b6p-6f, 0x1.f33c46p-6f, 0x1.104f6cp-5f,
    0x1.2700b6p-5f, 0x1.3db1fep-5f, 0x1.546348p-5f, 0x1.6b149p-5f, 0x1.81c5dap-5f, 0x1.987724p-5f,
    0x1.af286cp-5f, 0x1.987724p-5f, 0x1.81c5dap-5f, 0x1.6b149p-5f, 0x1.546348p-5f, 0x1.3db1fep-5f,
    0x1.2700b6p-5f, 0x1.104f6cp-5f, 0x1.f33c46p-6f, 0x1.c5d9b6p-6f, 0x1.987724p-6f, 0x1.6b149p-6f,
    0x1.3db1fep-6f, 0x1.104f6cp-6f, 0x1.c5d9b6p-7f, 0x1.6b149p-7f, 0x1.104f6cp-7f, 0x1.6b149p-8f,
    0x1.6b149p-9f, 0x1.58ed24p-9f, 0x1.58ed24p-8f, 0x1.02b1dap-7f, 0x1.58ed24p-7f, 0x1.af286cp-7f,
    0x1.02b1dap-6f, 0x1.2dcf7ep-6f, 0x1.58ed24p-6f, 0x1.840ac8p-6f, 0x1.af286cp-6f, 0x1.da461p-6f,
    0x1.02b1dap-5f, 0x1.1840acp-5f, 0x1.2dcf7ep-5f, 0x1.435e52p-5f, 0x1.58ed24p-5f, 0x1.6e7bf4p-5f,
    0x1.840ac8p-5f, 0x1.99999ap-5f, 0x1.861862p-5f, 0x1.72972ap-5f, 0x1.5f15f2p-5f, 0x1.4b94bap-5f,
    0x1.381382p-5f, 0x1.24924ap-5f, 0x1.111112p-5f, 0x1.fb1fb4p-6f, 0x1.d41d44p-6f, 0x1.ad1ad4p-6f,
    0x1.861862p-6f, 0x1.5f15f2p-6f, 0x1.381382p-6f, 0x1.111112p-6f, 0x1.d41d44p-7f, 0x1.861862p-7f,
    0x1.381382p-7f, 0x1.d41d44p-8f, 0x1.381382p-8f, 0x1.381382p-9f, 0x1.3076eep-9f, 0x1.3076eep-8f,
    0x1.c8b268p-8f, 0x1.3076eep-7f, 0x1.7c94aap-7f, 0x1.c8b268p-7f, 0x1.0a6812p-6f, 0x1.3076eep-6f,
    0x1.5685ccp-6f, 0x1.7c94aap-6f, 0x1.a2a38ap-6f, 0x1.c8b268p-6f, 0x1.eec144p-6f, 0x1.0a6812p-5f,
    0x1.1d6f8p-5f, 0x1.3076eep-5f, 0x1.437e5ep-5f, 0x1.5685ccp-5f, 0x1.698d3cp-5f, 0x1.7c94aap-5f,
    0x1.8f9c18p-5f, 0x1.7ba118p-5f, 0x1.67a616p-5f, 0x1.53ab16p-5f, 0x1.3fb014p-5f, 0x1.2bb512p-5f,
    0x1.17ba12p-5f, 0x1.03bf1p-5f, 0x1.df882p-6f, 0x1.b7921cp-6f, 0x1.8f9c18p-6f, 0x1.67a616p-6f,
    0x1.3fb014p-6f, 0x1.17ba12p-6f, 0x1.df882p-7f, 0x1.8f9c18p-7f, 0x1.3fb014p-7f, 0x1.df882p-8f,
    0x1.3fb014p-8f, 0x1.3fb014p-9f, 0x1.381382p-9f, 0x1.381382p-8f, 0x1.d41d44p-8f, 0x1.381382p-7f,
    0x1.861862p-7f, 0x1.d41d44p-7f, 0x1.11111p-6f, 0x1.381382p-6f, 0x1.5f15fp-6f, 0x1.861862p-6f,
    0x1.ad1ad2p-6f, 0x1.d41d44p-6f, 0x1.fb1fbp-6f, 0x1.11111p-5f, 0x1.24924ap-5f, 0x1.381382p-5f,
    0x1.4b94bap-5f, 0x1.5f15fp-5f, 0x1.72972ap-5f, 0x1.861862p-5f, 0x1.745d16p-5f, 0x1.62a1cep-5f,
    0x1.50e684p-5f, 0x1.3f2b38p-5f, 0x1.2d6feep-5f, 0x1.1bb4a4p-5f, 0x1.09f95ap-5f, 0x1.f07c1ep-6f,
    0x1.cd058ap-6f, 0x1.a98ef6p-6f, 0x1.861862p-6f, 0x1.62a1cep-6f, 0x1.3f2b38p-6f, 0x1.1bb4a4p-6f,
    0x1.f07c1ep-7f, 0x1.a98ef6p-7f, 0x1.62a1cep-7f, 0x1.1bb4a4p-7f, 0x1.a98ef6p-8f, 0x1.1bb4a4p-8f,
    0x1.1bb4a4p-9f, 0x1.0ecf56p-9f, 0x1.0ecf56p-8f, 0x1.9637p-8f, 0x1.0ecf56p-7f, 0x1.52832cp-7f,
    0x1.9637p-7f, 0x1.d9ead4p-7f, 0x1.0ecf56p-6f, 0x1.30a94p-6f, 0x1.52832cp-6f, 0x1.745d16p-6f,
    0x1.9637p-6f, 0x1.b810eap-6f, 0x1.d9ead4p-6f, 0x1.fbc4cp-6f, 0x1.0ecf56p-5f, 0x1.1fbc4ap-5f,
    0x1.30a94p-5f, 0x1.419636p-5f, 0x1.52832cp-5f, 0x1.63702p-5f, 0x1.745d16p-5f, 0x1.63702p-5f,
    0x1.52832cp-5f, 0x1.419636p-5f, 0x1.30a94p-5f, 0x1.1fbc4ap-5f, 0x1.0ecf56p-5f, 0x1.fbc4cp-6f,
    0x1.d9ead4p-6f, 0x1.b810eap-6f, 0x1.9637p-6f, 0x1.745d16p-6f, 0x1.52832cp-6f, 0x1.30a94p-6f,
    0x1.0ecf56p-6f, 0x1.d9ead4p-7f, 0x1.9637p-7f, 0x1.52832cp-7f, 0x1.0ecf56p-7f, 0x1.9637p-8f,
    0x1.0ecf56p-8f, 0x1.0ecf56p-9f, 0x1.0ecf56p-9f, 0x1.0ecf56p-8f, 0x1.9637p-8f, 0x1.0ecf56p-7f,
    0x1.52832cp-7f, 0x1.9637p-7f, 0x1.d9ead4p-7f, 0x1.0ecf56p-6f, 0x1.30a94p-6f, 0x1.52832cp-6f,
    0x1.745d16p-6f, 0x1.9637p-6f, 0x1.b810eap-6f, 0x1.d9ead4p-6f, 0x1.fbc4cp-6f, 0x1.0ecf56p-5f,
    0x1.1fbc4ap-5f, 0x1.30a94p-5f, 0x1.419636p-5f, 0x1.52832cp-5f, 0x1.63702p-5f, 0x1.745d16p-5f,
    0x1.63702p-5f, 0x1.52832cp-5f, 0x1.419636p-5f, 0x1.30a94p-5f, 0x1.1fbc4ap-5f, 0x1.0ecf56p-5f,
    0x1.fbc4cp-6f, 0x1.d9ead4p-6f, 0x1.b810eap-6f, 0x1.9637p-6f, 0x1.745d16p-6f, 0x1.52832cp-6f,
    0x1.30a94p-6f, 0x1.0ecf56p-6f, 0x1.d9ead4p-7f, 0x1.9637p-7f, 0x1.52832cp-7f, 0x1.0ecf56p-7f,
    0x1.9637p-8f, 0x1.0ecf56p-8f, 0x1.0ecf56p-9f, 0x1.03091cp-9f, 0x1.03091cp-8f, 0x1.848daap-8f,
    0x1.03091cp-7f, 0x1.43cb62p-7f, 0x1.848daap-7f, 0x1.c54ffp-7f, 0x1.03091cp-6f, 0x1.236a3ep-6f,
    0x1.43cb62p-6f, 0x1.642c86p-6f, 0x1.848daap-6f, 0x1.a4eeccp-6f, 0x1.c54ffp-6f, 0x1.e5b114p-6f,
    0x1.03091cp-5f, 0x1.1339acp-5f, 0x1.236a3ep-5f, 0x1.339adp-5f, 0x1.43cb62p-5f, 0x1.53fbf4p-5f,
    0x1.642c86p-5f, 0x1.555554p-5f, 0x1.467e26p-5f, 0x1.37a6f4p-5f, 0x1.28cfc4p-5f, 0x1.19f894p-5f,
    0x1.0b2164p-5f, 0x1.f89466p-6f, 0x1.dae608p-6f, 0x1.bd37a6p-6f, 0x1.9f8946p-6f, 0x1.81dae6p-6f,
    0x1.642c86p-6f, 0x1.467e26p-6f, 0x1.28cfc4p-6f, 0x1.0b2164p-6f, 0x1.dae608p-7f, 0x1.9f8946p-7f,
    0x1.642c86p-7f, 0x1.28cfc4p-7f, 0x1.dae608p-8f, 0x1.642c86p-8f, 0x1.dae608p-9f, 0x1.dae608p-10f,
    0x1.c71c72p-10f, 0x1.c71c72p-9f, 0x1.555556p-8f, 0x1.c71c72p-8f, 0x1.1c71c6p-7f, 0x1.555556p-7f,
    0x1.8e38e2p-7f, 0x1.c71c72p-7f, 0x1.0p-6f, 0x1.1c71c6p-6f, 0x1.38e38ep-6f, 0x1.555556p-6f,
    0x1.71c71ep-6f, 0x1.8e38e2p-6f, 0x1.aaaaaap-6f, 0x1.c71c72p-6f, 0x1.e38e38p-6f, 0x1.0p-5f,
    0x1.0e38e4p-5f, 0x1.1c71c6p-5f, 0x1.2aaaaap-5f, 0x1.38e38ep-5f, 0x1.471c72p-5f, 0x1.555556p-5f,
    0x1.471c72p-5f, 0x1.38e38ep-5f, 0x1.2aaaaap-5f, 0x1.1c71c6p-5f, 0x1.0e38e4p-5f, 0x1.0p-5f,
    0x1.e38e38p-6f, 0x1.c71c72p-6f, 0x1.aaaaaap-6f, 0x1.8e38e2p-6f, 0x1.71c71ep-6f, 0x1.555556p-6f,
    0x1.38e38ep-6f, 0x1.1c71c6p-6f, 0x1.0p-6f, 0x1.c71c72p-7f, 0x1.8e38e2p-7f, 0x1.555556p-7f,
    0x1.1c71c6p-7f, 0x1.c71c72p-8f, 0x1.555556p-8f, 0x1.c71c72p-9f, 0x1.c71c72p-10f, 0x1.bdd2b8p-10f,
    0x1.bdd2b8p-9f, 0x1.4e5e08p-8f, 0x1.bdd2b8p-8f, 0x1.16a3b2p-7f, 0x1.4e5e08p-7f, 0x1.86185ep-7f,
    0x1.bdd2b8p-7f, 0x1.f58d0ep-7f, 0x1.16a3b2p-6f, 0x1.3280dep-6f, 0x1.4e5e08p-6f, 0x1.6a3b36p-6f,
    0x1.86185ep-6f, 0x1.a1f58ap-6f, 0x1.bdd2b8p-6f, 0x1.d9afep-6f, 0x1.f58d0ep-6f, 0x1.08b51cp-5f,
    0x1.16a3b2p-5f, 0x1.249248p-5f, 0x1.3280dep-5f, 0x1.406f72p-5f, 0x1.4e5e08p-5f, 0x1.40fe1cp-5f,
    0x1.339e32p-5f, 0x1.263e46p-5f, 0x1.18de58p-5f, 0x1.0b7e6ep-5f, 0x1.fc3d02p-6f, 0x1.e17d2cp-6f,
    0x1.c6bd54p-6f, 0x1.abfd7cp-6f, 0x1.913da6p-6f, 0x1.767dccp-6f, 0x1.5bbdf4p-6f, 0x1.40fe1cp-6f,
    0x1.263e46p-6f, 0x1.0b7e6ep-6f, 0x1.e17d2cp-7f, 0x1.abfd7cp-7f, 0x1.767dccp-7f, 0x1.40fe1cp-7f,
    0x1.0b7e6ep-7f, 0x1.abfd7cp-8f, 0x1.40fe1cp-8f, 0x1.abfd7cp-9f, 0x1.abfd7cp-10f, 0x1.1b662p-9f,
    0x1.1b662p-8f, 0x1.a9192ep-8f, 0x1.1b662p-7f, 0x1.623fa8p-7f, 0x1.a9192ep-7f, 0x1.eff2b8p-7f,
    0x1.1b662p-6f, 0x1.3ed2e4p-6f, 0x1.623fa8p-6f, 0x1.85ac6cp-6f, 0x1.a9192ep-6f, 0x1.cc85f2p-6f,
    0x1.eff2b8p-6f, 0x1.09afbep-5f, 0x1.1b662p-5f, 0x1.2d1c82p-5f, 0x1.3ed2e4p-5f, 0x1.508946p-5f,
    0x1.623fa8p-5f, 0x1.73f608p-5f, 0x1.85ac6cp-5f, 0x1.9762cep-5f, 0x1.a9192ep-5f, 0x1.bacf92p-5f,
    0x1.95e8fp-5f, 0x1.71024ep-5f, 0x1.4c1bacp-5f, 0x1.27350cp-5f, 0x1.024e6ap-5f, 0x1.bacf92p-6f,
    0x1.71024ep-6f, 0x1.27350cp-6f, 0x1.bacf92p-7f, 0x1.27350cp-7f, 0x1.27350cp-8f,
};

constexpr FilterBand kBands[kNumBands] = {
    {3, 1, 0}, // band 0: 37.5 Hz
    {4, 1, 1}, // band 1: 50.0 Hz
    {5, 1, 2}, // band 2: 62.5 Hz
    {6, 1, 3}, // band 3: 75.0 Hz
    {7, 1, 4}, // band 4: 87.5 Hz
    {8, 1, 5}, // band 5: 100.0 Hz
    {9, 1, 6}, // band 6: 112.5 Hz
    {10, 1, 7}, // band 7: 125.0 Hz
    {11, 1, 8}, // band 8: 137.5 Hz
    {12, 1, 9}, // band 9: 150.0 Hz
    {13, 1, 10}, // band 10: 162.5 Hz
    {14, 1, 11}, // band 11: 175.0 Hz
    {15, 1, 12}, // band 12: 187.5 Hz
    {16, 1, 13}, // band 13: 200.0 Hz
    {17, 1, 14}, // band 14: 212.5 Hz
    {18, 1, 15}, // band 15: 225.0 Hz
    {19, 1, 16}, // band 16: 237.5 Hz
    {20, 1, 17}, // band 17: 250.0 Hz
    {21, 1, 18}, // band 18: 262.5 Hz
    {22, 1, 19}, // band 19: 275.0 Hz
    {23, 1, 20}, // band 20: 287.5 Hz
    {24, 1, 21}, // band 21: 300.0 Hz
    {25, 1, 22}, // band 22: 312.5 Hz
    {26, 1, 23}, // band 23: 325.0 Hz
    {27, 1, 24}, // band 24: 337.5 Hz
    {28, 1, 25}, // band 25: 350.0 Hz
    {29, 1, 26}, // band 26: 362.5 Hz
    {30, 1, 27}, // band 27: 375.0 Hz
    {31, 1, 28}, // band 28: 387.5 Hz
    {32, 1, 29}, // band 29: 400.0 Hz
    {33, 1, 30}, // band 30: 412.5 Hz
    {34, 1, 31}, // band 31: 425.0 Hz
    {35, 1, 32}, // band 32: 437.5 Hz
    {36, 1, 33}, // band 33: 450.0 Hz
    {37, 1, 34}, // band 34: 462.5 Hz
    {38, 2, 35}, // band 35: 475.0 Hz
    {39, 2, 37}, // band 36: 500.0 Hz
    {41, 1, 39}, // band 37: 512.5 Hz
    {42, 1, 40}, // band 38: 525.0 Hz
    {43, 1, 41}, // band 39: 537.5 Hz
    {44, 2, 42}, // band 40: 550.0 Hz
    {45, 2, 44}, // band 41: 575.0 Hz
    {47, 1, 46}, // band 42: 587.5 Hz
    {48, 2, 47}, // band 43: 600.0 Hz
    {49, 2, 49}, // band 44: 625.0 Hz
    {51, 2, 51}, // band 45: 637.5 Hz
    {52, 2, 53}, // band 46: 662.5 Hz
    {54, 2, 55}, // band 47: 675.0 Hz
    {55, 3, 57}, // band 48: 700.0 Hz
    {57, 2, 60}, // band 49: 725.0 Hz
    {59, 2, 62}, // band 50: 737.5 Hz
    {60, 3, 64}, // band 51: 762.5 Hz
    {62, 3, 67}, // band 52: 787.5 Hz
    {64, 2, 70}, // band 53: 812.5 Hz
    {66, 2, 72}, // band 54: 825.0 Hz
    {67, 3, 74}, // band 55: 850.0 Hz
    {69, 3, 77}, // band 56: 875.0 Hz
    {71, 4, 80}, // band 57: 900.0 Hz
    {73, 4, 84}, // band 58: 937.5 Hz
    {76, 3, 88}, // band 59: 962.5 Hz
    {78, 3, 91}, // band 60: 987.5 Hz
    {80, 4, 94}, // band 61: 1012.5 Hz
    {82, 4, 98}, // band 62: 1050.0 Hz
    {85, 4, 102}, // band 63: 1075.0 Hz
    {87, 4, 106}, // band 64: 1112.5 Hz
    {90, 4, 110}, // band 65: 1137.5 Hz
    {92, 5, 114}, // band 66: 1175.0 Hz
    {95, 5, 119}, // band 67: 1212.5 Hz
    {98, 4, 124}, // band 68: 1250.0 Hz
    {101, 4, 128}, // band 69: 1275.0 Hz
    {103, 6, 132}, // band 70: 1312.5 Hz
    {106, 6, 138}, // band 71: 1362.5 Hz
    {110, 5, 144}, // band 72: 1400.0 Hz
    {113, 5, 149}, // band 73: 1437.5 Hz
    {116, 6, 154}, // band 74: 1475.0 Hz
    {119, 6, 160}, // band 75: 1525.0 Hz
    {123, 6, 166}, // band 76: 1562.5 Hz
    {126, 7, 172}, // band 77: 1612.5 Hz
    {130, 7, 179}, // band 78: 1662.5 Hz
    {134, 7, 186}, // band 79: 1712.5 Hz
    {138, 7, 193}, // band 80: 1762.5 Hz
    {142, 7, 200}, // band 81: 1812.5 Hz
    {146, 8, 207}, // band 82: 1862.5 Hz
    {150, 8, 215}, // band 83: 1925.0 Hz
    {155, 8, 223}, // band 84: 1975.0 Hz
    {159, 8, 231}, // band 85: 2037.5 Hz
    {164, 8, 239}, // band 86: 2087.5 Hz
    {168, 9, 247}, // band 87: 2150.0 Hz
    {173, 10, 256}, // band 88: 2212.5 Hz
    {178, 10, 266}, // band 89: 2287.5 Hz
    {184, 9, 276}, // band 90: 2350.0 Hz
    {189, 10, 285}, // band 91: 2412.5 Hz
    {194, 11, 295}, // band 92: 2487.5 Hz
    {200, 11, 306}, // band 93: 2562.5 Hz
    {206, 11, 317}, // band 94: 2637.5 Hz
    {212, 12, 328}, // band 95: 2712.5 Hz
    {218, 12, 340}, // band 96: 2800.0 Hz
    {225, 12, 352}, // band 97: 2875.0 Hz
    {231, 13, 364}, // band 98: 2962.5 Hz
    {238, 13, 377}, // band 99: 3050.0 Hz
    {245, 13, 390}, // band 100: 3137.5 Hz
    {252, 14, 403}, // band 101: 3225.0 Hz
    {259, 15, 417}, // band 102: 3325.0 Hz
    {267, 15, 432}, // band 103: 3425.0 Hz
    {275, 15, 447}, // band 104: 3525.0 Hz
    {283, 15, 462}, // band 105: 3625.0 Hz
    {291, 16, 477}, // band 106: 3725.0 Hz
    {299, 17, 493}, // band 107: 3837.5 Hz
    {308, 17, 510}, // band 108: 3950.0 Hz
    {317, 18, 527}, // band 109: 4062.5 Hz
    {326, 19, 545}, // band 110: 4187.5 Hz
    {336, 19, 564}, // band 111: 4312.5 Hz
    {346, 19, 583}, // band 112: 4437.5 Hz
    {356, 20, 602}, // band 113: 4562.5 Hz
    {366, 21, 622}, // band 114: 4700.0 Hz
    {377, 21, 643}, // band 115: 4837.5 Hz
    {388, 22, 664}, // band 116: 4975.0 Hz
    {399, 23, 686}, // band 117: 5125.0 Hz
    {411, 23, 709}, // band 118: 5275.0 Hz
    {423, 24, 732}, // band 119: 5425.0 Hz
    {435, 25, 756}, // band 120: 5587.5 Hz
    {448, 26, 781}, // band 121: 5750.0 Hz
    {461, 26, 807}, // band 122: 5925.0 Hz
    {475, 27, 833}, // band 123: 6087.5 Hz
    {488, 28, 860}, // band 124: 6275.0 Hz
    {503, 29, 888}, // band 125: 6450.0 Hz
    {517, 30, 917}, // band 126: 6650.0 Hz
    {533, 30, 947}, // band 127: 6837.5 Hz
    {548, 32, 977}, // band 128: 7037.5 Hz
    {564, 33, 1009}, // band 129: 7250.0 Hz
    {581, 33, 1042}, // band 130: 7462.5 Hz
    {598, 34, 1075}, // band 131: 7675.0 Hz
    {615, 36, 1109}, // band 132: 7900.0 Hz
    {633, 37, 1145}, // band 133: 8137.5 Hz
    {652, 37, 1182}, // band 134: 8375.0 Hz
    {671, 39, 1219}, // band 135: 8612.5 Hz
    {690, 40, 1258}, // band 136: 8875.0 Hz
    {711, 41, 1298}, // band 137: 9125.0 Hz
    {731, 43, 1339}, // band 138: 9400.0 Hz
    {753, 43, 1382}, // band 139: 9675.0 Hz
    {775, 45, 1425}, // band 140: 9950.0 Hz
    {797, 47, 1470}, // band 141: 10250.0 Hz
    {821, 48, 1517}, // band 142: 10550.0 Hz
    {845, 36, 1565}, // band 143: 10862.5 Hz
};

static_assert(sizeof(kWeights) / sizeof(kWeights[0]) == 1601);

} // namespace

std::span<const FilterBand, kNumBands> filterbankBands() noexcept {
    return kBands;
}

std::span<const float> filterbankWeights() noexcept {
    return kWeights;
}

} // namespace takt4::features
