#!/usr/bin/env python3
"""Dump madmom's filterbank as the C++ table src/core/features/filterbank_table.cpp.

HANDOFF §5.2: the filterbank is never reimplemented; the matrix madmom actually applies
is dumped once and compiled in. Run this after changing tools/requirements.txt (a new
madmom or numpy) and commit the result together with regenerated goldens.

The (882, 144) matrix is sparse: every band is one contiguous triangle of bins, 1601
weights in all. The table stores each band as (first bin, bin count, offset into one
flat weight array), with the weights as hexadecimal float literals so the compiler
reproduces the float32 values bit for bit. The script parses its own output back into a
dense matrix and compares it with madmom's before it is happy.

    python tools/dump_filterbank.py [--out PATH]
"""

import argparse
import importlib.metadata
import json
import re
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from beatnet_features import (  # noqa: E402
    FRAME_SIZE,
    HOP_SIZE,
    NUM_BANDS,
    NUM_BINS,
    SAMPLE_RATE,
    FeaturePipeline,
)

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "src" / "core" / "features" / "filterbank_table.cpp"


def madmom_source():
    """'<commit>' for a git install, or the version, for the generated file's header."""
    dist = importlib.metadata.distribution("madmom")
    direct_url = dist.read_text("direct_url.json")
    if direct_url:
        info = json.loads(direct_url)
        commit = info.get("vcs_info", {}).get("commit_id")
        if commit:
            return f"{info.get('url', 'git')} @ {commit}"
    return f"madmom {dist.version}"


def float32_literal(value):
    """A C++ float literal that is exactly this float32 value."""
    value = float(np.float32(value))
    if value == 0.0:
        return "0.0f"
    text = float.hex(value)  # e.g. 0x1.8d30000000000p-7
    mantissa, exponent = text.split("p")
    mantissa = mantissa.rstrip("0")
    if mantissa.endswith("."):
        mantissa += "0"
    literal = f"{mantissa}p{exponent}f"
    if np.float32(float.fromhex(literal[:-1])) != np.float32(value):
        raise AssertionError(f"literal {literal} does not round-trip {value!r}")
    return literal


def bands_of(fb):
    """[(first_bin, weights)] per column, checking that each column is one contiguous run."""
    bands = []
    for b in range(fb.shape[1]):
        nonzero = np.flatnonzero(fb[:, b])
        if len(nonzero) == 0:
            raise AssertionError(f"band {b} is empty")
        first, last = int(nonzero[0]), int(nonzero[-1])
        if last - first + 1 != len(nonzero):
            raise AssertionError(f"band {b} has gaps between bins {first} and {last}")
        bands.append((first, fb[first : last + 1, b].copy()))
    return bands


def render(fb, bands, source):
    weights = np.concatenate([w for _, w in bands])
    lines = [
        "// Generated by tools/dump_filterbank.py; do not edit. Regenerate from the Python side.",
        "//",
        "// madmom's LogarithmicFilterbank as applied in the BeatNet+ front end (HANDOFF §5.2):",
        f"// the {NUM_BINS} bins of a {FRAME_SIZE}-point STFT at {SAMPLE_RATE} Hz (DC up to, not including,",
        f"// Nyquist) folded into {NUM_BANDS} bands, 24 per octave between 30 Hz and 17000 Hz around",
        "// 440 Hz, every filter normalised to sum 1, duplicate filters removed. Each band is one",
        "// contiguous triangle of bins. The weights are hexadecimal float literals, so they are",
        "// the float32 values madmom uses, exactly.",
        "//",
        f"// Source: {source}; numpy {np.__version__}.",
        "",
        '#include "core/features/filterbank.hpp"',
        "",
        "namespace takt4::features {",
        "",
        "namespace {",
        "",
        f"constexpr float kWeights[{len(weights)}] = {{",
    ]
    per_line = 6
    for i in range(0, len(weights), per_line):
        chunk = ", ".join(float32_literal(w) for w in weights[i : i + per_line])
        lines.append(f"    {chunk},")
    lines += ["};", "", f"constexpr FilterBand kBands[kNumBands] = {{"]
    offset = 0
    for b, (first, w) in enumerate(bands):
        centre = fb[:, b].argmax() * SAMPLE_RATE / FRAME_SIZE
        lines.append(f"    {{{first}, {len(w)}, {offset}}}, // band {b}: {centre:.1f} Hz")
        offset += len(w)
    lines += [
        "};",
        "",
        f"static_assert(sizeof(kWeights) / sizeof(kWeights[0]) == {offset});",
        "",
        "} // namespace",
        "",
        "std::span<const FilterBand, kNumBands> filterbankBands() noexcept {",
        "    return kBands;",
        "}",
        "",
        "std::span<const float> filterbankWeights() noexcept {",
        "    return kWeights;",
        "}",
        "",
        "} // namespace takt4::features",
        "",
    ]
    return "\n".join(lines)


def parse_back(text):
    """Rebuild the dense matrix from the generated source, independently of render()."""
    weights_text = re.search(r"kWeights\[(\d+)\] = \{(.*?)\};", text, re.S)
    bands_text = re.search(r"kBands\[kNumBands\] = \{(.*?)\};", text, re.S)
    if not weights_text or not bands_text:
        raise AssertionError("could not find the tables in the generated text")
    literals = re.findall(r"(0x[0-9a-f.]+p[+-]\d+|0\.0)f", weights_text.group(2))
    if len(literals) != int(weights_text.group(1)):
        raise AssertionError(f"{len(literals)} literals for a table of {weights_text.group(1)}")
    weights = np.array([float.fromhex(lit) if lit.startswith("0x") else 0.0 for lit in literals], dtype=np.float32)
    dense = np.zeros((NUM_BINS, NUM_BANDS), dtype=np.float32)
    entries = re.findall(r"\{(\d+), (\d+), (\d+)\}", bands_text.group(1))
    if len(entries) != NUM_BANDS:
        raise AssertionError(f"{len(entries)} bands in the generated text")
    for b, (first, count, offset) in enumerate(entries):
        first, count, offset = int(first), int(count), int(offset)
        dense[first : first + count, b] = weights[offset : offset + count]
    return dense


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"output file (default: {DEFAULT_OUT})")
    args = parser.parse_args()

    # The filterbank is built from the STFT's bin frequencies on the first run, so run.
    pipeline = FeaturePipeline()
    pipeline.features(np.random.default_rng(0).standard_normal(SAMPLE_RATE).astype(np.float32) * 0.1)
    fb = pipeline.filterbank()

    column_sums = fb.sum(axis=0)
    if not np.allclose(column_sums, 1.0, atol=1e-6):
        raise AssertionError(f"column sums are not 1: {column_sums.min()}..{column_sums.max()}")
    if (np.count_nonzero(fb, axis=1) > 2).any():
        raise AssertionError("a bin contributes to more than two bands")

    bands = bands_of(fb)
    text = render(fb, bands, madmom_source())
    if not np.array_equal(parse_back(text), fb):
        raise AssertionError("the generated table does not reproduce madmom's matrix")

    args.out.write_text(text, encoding="utf-8", newline="\n")
    widths = [len(w) for _, w in bands]
    print(f"wrote {args.out}")
    print(f"  {fb.shape[0]} bins x {fb.shape[1]} bands, {sum(widths)} weights, "
          f"band widths {min(widths)}..{max(widths)} bins, "
          f"bins {bands[0][0]}..{bands[-1][0] + widths[-1] - 1} used, "
          f"frames every {HOP_SIZE} samples")


if __name__ == "__main__":
    main()
