#!/usr/bin/env python3
"""Turns a binary asset into a C++ source file that carries its bytes.

Why this exists. takt4 ships as one executable somebody copies to a stick and carries to a
venue. The neural weights and the state space are the two files it cannot start without, so
they go *inside* it rather than beside it; an app that hunts for a folder is an app that
stops working the first time somebody moves it.

Why string literals and not an array. A `const unsigned char[] = {0x00, 0x01, ...}` with
three million entries is the obvious way and is the wrong one: MSVC spends minutes and a
great deal of memory on a brace initialiser that size. A string literal costs the parser
almost nothing, and the linker stores it identically.

Every byte is written as `\\xNN`, including the ones that are ordinary printable characters.
That is deliberate: a hex escape in C++ is maximal-munch, so `"\\x4" "1"` and `"\\x41"` are
different lengths and a literal `A` after `\\x4` would silently join it. Escaping everything
means no byte can ever extend the escape before it. It costs four source characters per
byte, which is a source file about four times the size of the asset and still parses in
under a second.

The chunking is MSVC's limit: a single narrow string literal may not exceed 16,380
characters (C2026), so the data is cut into pieces under that and stitched back together
once, on first use.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

# Comfortably under MSVC's 16,380-character string literal limit (C2026), and a round
# number so the generated file is easy to eyeball.
CHUNK_BYTES = 16000


def escape(chunk: bytes) -> str:
    return "".join(f"\\x{byte:02x}" for byte in chunk)


def generate(data: bytes, name: str, source: pathlib.Path) -> str:
    chunks = [data[at : at + CHUNK_BYTES] for at in range(0, len(data), CHUNK_BYTES)]
    lines = [
        "// Generated by tools/embed_asset.py. Do not edit, and do not commit:",
        f"// this is built from assets/{source.parent.name}/{source.name} every time.",
        "//",
        "// See that script for why the bytes are a string literal rather than an array,",
        "// and why every one of them is escaped.",
        "",
        '#include "core/assets/embedded.hpp"',
        "",
        "#include <cstddef>",
        "#include <cstring>",
        "#include <iterator>",
        "#include <vector>",
        "",
        "namespace takt4::assets {",
        "namespace {",
        "",
        f"constexpr std::size_t kTotalBytes = {len(data)};",
        "",
        "// The `char` type is what a string literal is; the bytes are copied straight out of",
        "// it and never read as characters.",
        "const char* const kChunks[] = {",
    ]
    for chunk in chunks:
        lines.append(f'    "{escape(chunk)}",')
    lines.append("};")
    lines.append("")
    lines.append("const std::size_t kChunkBytes[] = {")
    for chunk in chunks:
        lines.append(f"    {len(chunk)},")
    lines.append("};")
    lines.extend(
        [
            "",
            "/// Stitched once, on first use, and kept for the life of the program. The copy is a",
            "/// few megabytes and happens before the window opens; the alternative is handing the",
            "/// loaders a list of pieces, which would spread the chunking into code that has no",
            "/// business knowing about MSVC's string limit.",
            "const std::vector<std::byte>& blob() {",
            "    static const std::vector<std::byte> bytes = [] {",
            "        std::vector<std::byte> out(kTotalBytes);",
            "        std::size_t at = 0;",
            "        for (std::size_t i = 0; i < std::size(kChunks); ++i) {",
            "            std::memcpy(out.data() + at, kChunks[i], kChunkBytes[i]);",
            "            at += kChunkBytes[i];",
            "        }",
            "        return out;",
            "    }();",
            "    return bytes;",
            "}",
            "",
            "} // namespace",
            "",
            f"std::span<const std::byte> {name}() {{",
            "    return blob();",
            "}",
            "",
            "} // namespace takt4::assets",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=pathlib.Path, help="the binary to embed")
    parser.add_argument("output", type=pathlib.Path, help="the .cpp to write")
    parser.add_argument(
        "--name",
        required=True,
        help="the takt4::assets function to define, e.g. weights",
    )
    args = parser.parse_args()

    data = args.source.read_bytes()
    if not data:
        print(f"embed_asset: {args.source} is empty", file=sys.stderr)
        return 1

    text = generate(data, args.name, args.source)
    # Only when it changed: this runs from a build rule, and rewriting the file every time
    # would rebuild a translation unit of several megabytes on every single build.
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if args.output.exists() and args.output.read_text(encoding="utf-8") == text:
        return 0
    args.output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
