# Writes the header that says which commit a build came from — `git describe --tags --dirty
# --always`, the audit's ask, so a binary names its commit and whether the tree it was built
# from had changes nobody committed.
#
# Run as a script on every build (src/core/CMakeLists.txt) rather than once at configure
# time, since a configured value would go on naming the commit the tree was configured at.
# The file is rewritten only when the text changes, so a build in which nothing moved
# recompiles nothing.
#
#   cmake -DGIT=<git> -DSOURCE=<repo> -DOUT=<header> -P cmake/git_describe.cmake

set(describe "")
if(GIT)
  execute_process(
    COMMAND "${GIT}" describe --tags --dirty --always
    WORKING_DIRECTORY "${SOURCE}"
    OUTPUT_VARIABLE describe
    RESULT_VARIABLE result
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
  if(NOT result EQUAL 0)
    set(describe "")
  endif()
endif()
if(describe STREQUAL "")
  # A source archive with no .git, or no git on PATH: said plainly rather than left blank.
  set(describe "unknown")
endif()

set(content "// Generated by cmake/git_describe.cmake on every build; do not edit.\n#pragma once\n\n#define TAKT4_GIT_DESCRIBE \"${describe}\"\n")
set(existing "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" existing)
endif()
if(NOT existing STREQUAL content)
  file(WRITE "${OUT}" "${content}")
endif()
