#pragma once

#include <cstddef>
#include <span>

namespace takt4::assets {

/// The two blobs takt4 cannot start without, compiled into the program.
///
/// HANDOFF §8 Phase 7 had these resolved next to the executable by an installer. They are
/// *inside* it instead, which is the same intent taken one step further: the application is
/// one file, and copying that file somewhere else copies a working application. An app that
/// looks for a folder beside itself is an app that breaks the first time somebody moves the
/// exe and not the folder — and that is exactly what happened to the copy on D:\, which went
/// on reading its weights out of the source tree it was built in.
///
/// The bodies are generated at build time by `tools/embed_asset.py` from `assets/weights`
/// and `assets/statespace`, so the committed blobs remain the single source of truth and
/// nothing has to be regenerated by hand when they change.
///
/// `takt4-cli` links these too, wherever they are built: it ships beside the app, and a
/// console that read its weights from the source tree failed on every other machine (the
/// audit's H19). It still takes any other set by name or path. The test binaries do not link
/// them: they point at the files, and want no three megabytes of literal in every link.

/// The BeatNet+ weights — `assets/weights/electronic.bin` since 0.9.1 (`generic` fine-tuned
/// on the operator's library, TRACKING-PROPOSAL.md §7.13), in `ModelWeights::fromBytes` form.
std::span<const std::byte> weights();

/// The bar-pointer state space — `assets/statespace/default.bin`, for
/// `StateSpaceModel::fromBytes`.
std::span<const std::byte> stateSpace();

} // namespace takt4::assets
